version: "3.6"
services:
  java-server:
    build: ./backend/docker/java
    ports:
      - 8080:8080
      - 12000:3000
    tty: true
    volumes:
      - ./backend/server/src:/usr/src:cached
      - ./backend/server/app:/usr/src/app:cached
  java-client:
    build: ./frontend/docker/java
    ports:
      - 8081:8081
    tty: true
    volumes:
      - ./frontend/front/src:/usr/src:cached
