version: "3.6"
services:
  java-server:
    build: ./backend/docker/java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend/server/src:/usr/src:cached
  java-client:
    build: ./frontend/docker/java
    ports:
      - 8081:8081
    tty: true
    volumes:
      - ./frontend/front/src:/usr/src:cached
  next-client:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 12000:3000
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules:
